### ISSUE TITLE
Camera plugin segfaults

### ISSUE THREAD

**Issue by jdolan** [TTimo/GtkRadiant#239]
When trying to use the camera plugin, adding a new camera to a map causes a segfault. Here's the bt:

```Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000000
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000104681d61 in glLabeledPoint (color=@0x1046c6640, point=@0x10ae8a904, size=5, label=0x10469facb "Fixed point") at splines.cpp:99
#2  0x000000010468a600 in idFixedPosition::draw (this=0x10ae8a8a0, editMode=true) at splines.h:538
#3  0x000000010469c779 in idCameraDef::draw (this=0x1046ae220, editMode=true) at splines.h:1020
#4  0x000000010469b4a8 in CRenderer::Draw3D (this=0x1041561d0) at renderer.cpp:128
#5  0x000000010469b175 in non-virtual thunk to CRenderer::Draw3D() () at splines.h:42
#6  0x000000010004cddd in Draw3DPluginEntities () at glinterface.cpp:82
#7  0x000000010003c168 in CamWnd::Cam_Draw (this=0x1030a5800) at camwindow.cpp:1554
#8  0x000000010003c933 in CamWnd::OnExpose (this=0x1030a5800) at camwindow.cpp:1653
#9  0x000000010004e060 in expose (widget=0x103095320, event=0x7fff5fbff190, data=0x1030a5800) at glwindow.cpp:60
#10 0x0000000100834e6e in _gtk_marshal_BOOLEAN__BOXED ()
#11 0x000000010111fe61 in g_closure_invoke ()
#12 0x000000010113291b in signal_emit_unlocked_R ()
#13 0x00000001011339c4 in g_signal_emit_valist ()
#14 0x0000000101133cd6 in g_signal_emit ()
#15 0x000000010092a5ef in gtk_widget_event_internal ()
#16 0x0000000100832ee6 in gtk_main_do_event ()
#17 0x0000000100bde6ff in _gdk_window_process_updates_recurse ()
#18 0x0000000100bdf058 in gdk_window_process_updates_internal ()
#19 0x0000000100bdebec in gdk_window_process_all_updates ()
#20 0x0000000100bdf1e5 in gdk_window_update_idle ()
#21 0x0000000100bc354d in gdk_threads_dispatch ()
#22 0x00000001011927f4 in g_main_context_dispatch ()
#23 0x0000000101192afc in g_main_context_iterate ()
#24 0x0000000101192d81 in g_main_loop_run ()
#25 0x00000001008327f0 in gtk_main ()
#26 0x00000001000711ba in main (argc=1, argv=0x7fff5fbffaa8) at main.cpp:905

(gdb) ```

Is this thing used? Should we bother fixing it, or just lose it?

**Comment by Pan7** [comment]
Its crashing when you click plugins -> camera -> New Fixed Camera
The plugin can't access the OpenGL functions.
